### ISSUE TITLE
cannot import name 'lib' from 'model.roi_pooling._ext._roi_pooling'

### ISSUE THREAD

**Issue by efgagfecdb** [naver/lcrnet-v2-improved-ppi#2]
I got stuck with the error below:
i$ python demo.py Human3.6-17J-ResNet50 Directions1_S11_C1_1.jpg 0
>>
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    from detect_pose import detect_pose
  File "/home/seo/workspace/lcrnet-v2-improved-ppi/detect_pose.py", line 37, in <module>
    from lcrnet_model import LCRNet
  File "/home/seo/workspace/lcrnet-v2-improved-ppi/lcrnet_model.py", line 30, in <module>
    from model.roi_pooling.functions.roi_pool import RoIPoolFunction
  File "/home/seo/workspace/lcrnet-v2-improved-ppi/model/roi_pooling/functions/roi_pool.py", line 3, in <module>
    from .._ext import roi_pooling
  File "/home/seo/workspace/lcrnet-v2-improved-ppi/model/roi_pooling/_ext/roi_pooling/__init__.py", line 3, in <module>
    from ..roi_pooling import lib as _lib, ffi as _ffi
**ImportError: cannot import name 'lib' from 'model.roi_pooling._ext._roi_pooling' (/home/seo/workspace/lcrnet-v2-improved-ppi/model/roi_pooling/_ext/_roi_pooling/__init__.py)**

in my guess, this error is due to detectron.pytorch 

but does anyone here solved this problem? it should be dealt with anyway, to run lcrnet++

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

You indeed need to install Detectron.pytorch following their instructions and add it to your pythonpath or add a softlink in your directory.

As an alternative, you can use DOPE which will also output keypoints for detected hands and faces: https://github.com/naver/dope

Best regards
Philippe
